Stallionboi by Sarokcat n Verath begins here.

"Adds a Stallionboi to Flexible Survival's Wandering Monsters table, with impreg chance"

Section 1 - Creature Responses

to say Stallionboi wins:
	project the Figure of Stallionboi_hard_icon;
	if Player is female:
		say "     The slutty stallionboi gives a rather girlish squeal of glee as you finally give up your futile attempt at resisting the strange horseboi's assault. 'We are going to make such a pretty little stallionslut out of you!' He gushes happily, as he grabs your arms and practically drags you through the halls with a lusty smirk on his face, his sexy black horselike tail swishing eagerly in front of you as he drags you along. Catching your breath slightly, you try to open your mouth to protest your rough handling only to stumble as he stops in front of a door and throws it open wide. You get a confused glimpse of several equine heads turning in your direction as he shoves you inside, his call of 'Boys, we got a new playtoy!' fills your ears for a second, before the sound of loud partially equine squealing drowns out anything else.";
		say "     You gasp and try to struggle as a large number of the vaguely feminine stallionbois descend eagerly on your already aroused body, their hands groping and stroking you all over even as the aroused musk of a roomful of horny equines washes over you. Unable to resist their advances, you find yourself moaning wantonly as they begin to tease and play with your body, rubbing their thick erect equine cocks up against you as you find yourself hauled down onto the bed. It isn't long before they have those wonderful equine members buried in your all too eager body either, causing you to moan helplessly around the equine rod filling your mouth as your increasingly sex crazed body is filled by the strangely sexy beasts. Before long you find yourself losing track of anything but the hands stroking and playing with your overstimulated body, and the thick horsemeat rubbing up against you, or plunging into your all too eager holes.";
		WaitLineBreak;
		say "     Completely losing track of how many times you are taken by the sexy male slutbois, or in how many ways, your pussy and ass are stuffed throughout the night by who knows how many different partners. Eventually you find yourself orgasming for the final time, and are carried away into unconsciousness on a wave of sexual bliss, your body still being used by the many sexy equines the entire time. When you wake up you find yourself still in the same room, though someone took time to move you off to a more comfortable position on the side of the room. Looking around, you see the room is filled with the bodies of a number of those exhausted little slut stallions, most of them passed out still in a pile or holding each other close, the strange orgy obviously having continued long after you passed out.";
		say "     The scent of sex and equines fills the air, causing you to moan slightly as your well used body tries to respond in the way they were training it too, your pussy clenching eagerly as your lust to experience more of that wonderful pleasure begins to grow between your legs. Fortunately you still manage to retain just enough willpower to take the opportunity to slip out the door while they are all unconscious, staggering drunkenly back towards the entrance to this crazy and sensual place even while still covered with their seed and smelling of sex.";
	else:
		say "     The slutty stallionboi gives a rather girlish squeal of glee as you finally give up your futile attempt at resisting the strange horseboi's assault. 'We are going to make such a pretty little stallionslut out of you!' He gushes happily, as he grabs your arms and practically drags you through the halls with a lusty smirk on his face, his sexy black horselike tail swishing eagerly in front of you as he drags you along. Catching your breath slightly, you try to open your mouth to protest your rough handling only to stumble as he stops in front of a door and throws it open wide. You get a confused glimpse of several equine heads turning in your direction as he shoves you inside, his call of 'Boys, we got a new playtoy!' fills your ears for a second, before the sound of loud partially equine squealing drowns out anything else.";
		say "     You gasp and try to struggle as a large number of the vaguely feminine stallionbois descend eagerly on your already aroused body, their hands groping and stroking you all over even as the aroused musk of a roomful of horny equines washes over you. Unable to resist their advances, you find yourself moaning wantonly as they begin to tease and play with your body, rubbing their thick erect equine cocks up against you as you find yourself hauled down onto the bed. It isn't long before they have those wonderful equine members buried in your all too eager body either, causing you to moan helplessly around the equine rod filling your mouth as your increasingly sex crazed body is filled by the strangely sexy beasts. Before long you find yourself losing track of anything but the hands stroking and playing with your overstimulated body, and the thick horsemeat rubbing up against you, or plunging into your all too eager holes.";
		WaitLineBreak;
		say "     Completely lose track of how many times you are taken by the sexy male slutbois, or in how many ways, your mouth and ass are stuffed throughout the night by who knows how many different partners, even while your own [Cock of Player] rod is lavished with attention again and again, as they wring orgasm after orgasm out of you. Eventually you find yourself orgasming for the final time, and are carried away into unconsciousness on a wave of sexual bliss, your body still being used by the many sexy equines the entire time. When you wake up you find yourself still in the same room, though someone took time to move you off to a more comfortable position on the side of the room. Looking around, you see the room is filled with the bodies of a number of those exhausted little slut stallions, most of them passed out still in a pile or holding each other close, the strange orgy obviously having continued long after you passed out.";
		say "     The scent of sex and equines fills the air, causing you to moan slightly as your well used body tries to respond in the way they were training it too, your cock twitching as it tries to revive itself for another round, even as your lust to experience more of that wonderful pleasure begins to grow between your legs. Fortunately you still manage to retain just enough willpower to take the opportunity to slip out the door while they are all unconscious, staggering drunkenly back towards the entrance to this crazy and sensual place even while still covered with their seed and smelling of sex.";
	CreatureSexAftermath "Player" receives "PussyFuck" from "Stallionboi";
	CreatureSexAftermath "Player" receives "AssFuck" from "Stallionboi";
	CreatureSexAftermath "Player" receives "PussyFuck" from "Stallionboi";
	CreatureSexAftermath "Player" receives "AssFuck" from "Stallionboi";

To say Stallionboi loses:
	project the Figure of Stallionboi_hard_icon;
	say "     [bold type]Being the victor of your scuffle, you decide that you'll:[roman type][line break]";
	let StallionboiWin_Choices be a list of text;
	if Player is male:
		add "Use that bratty mouth by plugging it with your cock." to StallionboiWin_Choices;
		add "Give him a light spanking, followed by a creamy anal filling." to StallionboiWin_Choices;
	if Player is female:
		add "Use that bratty mouth by putting it to work on your pussy." to StallionboiWin_Choices;
		add "Ride that big equine cock with your pussy." to StallionboiWin_Choices;
	add "Give him a light spanking, then send him away without release." to StallionboiWin_Choices;
	add "Just send him packing." to StallionboiWin_Choices;
	let StallionboiWin_Choice be what the player chooses from StallionboiWin_Choices;
	if StallionboiWin_Choice is:
		-- "Use that bratty mouth by plugging it with your cock.":
			LineBreak;
			Stallionboi_oral_cock;
		-- "Give him a light spanking, followed by a creamy anal filling.":
			LineBreak;
			Stallionboi_spank_creampie;
		-- "Ride that big equine cock with your ass.":
			LineBreak;
			Stallionboi_ride_anal;
		-- "Use that bratty mouth by putting it to work on your pussy.":
			LineBreak;
			Stallionboi_oral_pussy;
		-- "Ride that big equine cock with your pussy.":
			LineBreak;
			Stallionboi_ride_pussy;
		-- "Give him a light spanking, then send him away without release.":
			LineBreak;
			Stallionboi_spank_deny;
		-- "Just send him packing.":
			project the Figure of Stallionboi_clothed_icon;
			LineBreak;
			say "     Driven back by your powerful resistance, the stallionboi groans as he staggers backwards and shoots you a rather dirty and sullen look, before bursting into tears as he says '[one of]Well you didn't have to be so mean!'[or]Maybe you will be more fun next time sexy,'[or]Why don't you want to fuck me?'[or]Damn sweetie, that's a little rough for me, maybe you should try one of the donkeys,'[at random] before staggering off down the corridor, shooting you a last teasing glance over his shoulder as he does so.";

to Stallionboi_oral_cock:
	project the Figure of Stallionboi_hard_icon;
	say "     Grabbing the black leather collar around his neck, you apply a firm downward pressure that immediately halts his teasing bravado. The stallion's eyes go wide, a mix of surprise and sudden, eager compliance flashing across his features as he sinks gracefully to his knees. The dark chocolate fur of his slender frame contrasts sharply against the pale floor, his digitigrade legs clad in their sheer black stockings tucked neatly beneath him. He looks up through long, feminine lashes, his long tail swishing with a frantic, rhythmic excitement that betrays his true desires. 'Oh, you want me right here, sir?' he whispers, his voice taking on a delicate, breathy pitch as his blue-frosted hair tumbles over his shoulders. His massive equine manhood, unable to be contained by the skimpy blue pouch, throbs heavily against his stomach.";
	say "     You answer by presenting your rigid, dripping [Cock of Player] erection directly to his face, making it clear that his mouth is required for service. His leaf-shaped ears pin back in sheer delight, his slender, half-equine muzzle parting to reveal a slick, pink tongue. With an expert, practiced motion, he leans forward and takes the blunt head of your shaft past his lips, a muffled, appreciative hum vibrating deep within his throat. The sensation is incredible, his long muzzle providing a tight, enveloping warmth that surrounds you completely. The stallion doesn't just suck; he uses the unique shape of his jaw to create a deep, pulsing vacuum, his tongue swirling around the sensitive ridge of your crown while his lips seal tight around your base, effectively shutting up his bratty mouth.";
	WaitLineBreak;
	say "     Establishing a commanding rhythm, you begin to thrust into the dark, wet tunnel of his throat, using his mouth to completely dominate his senses. The stallion is a masterpiece of submissive compliance, his hands reaching down to stroke his own massive, leaking cock while he takes every inch of your length without complaint. Copious amounts of clear pre-cum drip from his flared tip, creating a slick, growing puddle on the floor beneath him as he works himself into a frenzy. Every time you bottom out against the back of his throat, his shoulders shudder, and a heavy, wet squelch echoes in the quiet space. He is entirely focused on his task, his green eyes rolled up to watch you as he swallows your thrusts, his long tail thrashing wildly behind him in a display of unadulterated lust.";
	say "     The relentless, deep-throat friction drives the pressure in your groin to a shattering peak. With a guttural groan, your hips snap forward, burying your shaft to the hilt as your climax erupts into his eager throat. The stallion's neck visibly bulges as he gulps down the thick, pulsing torrent of your seed, a muffled squeal of ecstasy trapped behind his closed lips. At the exact same moment, his own hand pumps his massive equine cock in a blur of motion, sending heavy, splashing ropes of creamy fluid cascading onto the floor to join the puddle of his pre-cum. You remain buried for a long moment, savoring the final, tight pulls of his throat muscles before slowly pulling free with a loud, wet pop. Wiping a stray smear of your release from his chin, you adjust your clothes and step away, leaving the panting, dazed femboy still kneeling in his own sticky mess, a thoroughly satisfied grin plastered across his face.";
	CreatureSexAftermath "Stallionboi" receives "OralCock" from "Player";

to Stallionboi_spank_creampie:
	project the Figure of Stallionboi_hard_icon;
	say "     Grabbing the black leather collar around his neck, you spin the flustered stallion around and press him firmly but gently against the nearest wall. His confident, teasing bravado instantly melts into a flushed, eager submission as he realizes you have called his bluff. The dark chocolate fur of his slender back arches gracefully under your hands, his long black tail swishing with a frantic, rhythmic excitement. He leans into the cold plaster without a single complaint, his hands braced flat against the surface while his digitigrade hooves shift in their thigh-high black stockings. 'Oh, my,' he breathes, his voice taking on a delicate, breathy pitch that perfectly matches his feminine aesthetic. 'Are you going to punish a bad little brat?'";
	say "     A playful smirk touches your lips as you deliver a sharp, stinging slap to his rounded rear, the impact producing a loud clap that echoes down the hallway. He lets out a high-pitched, theatrical yelp, his hips bucking backward into your hand to invite another strike. You oblige with a series of rhythmic love taps, reddening the skin under his coat just above the thin blue strap of his thong. The light spanking does exactly what you intended; the front of his skimpy pouch bulges impossibly, unable to contain the heavy, flaring head of his equine manhood as it slips free. Copious amounts of clear pre-cum drip from his flared tip, spotting the floor beneath him while he whimpers in a daze of over-stimulated pleasure. 'Please, sir, that stings,' he whines, though his eager grinding against the wall tells a completely different story.";
	WaitLineBreak;
	say "     Slipping your fingers beneath the pale blue silk of his thong, you yank the fabric aside to fully expose his tight, puckered entrance. The slickness from his own leaking shaft is easily gathered and smeared across his rear, providing an effortless lubricant for the breach. Pressing the broad head of your rigid [Cock of Player] shaft against his ring of muscle, you push forward with a slow, deliberate momentum. A loud, wet pop resounds as the well-experienced sphincter gives way, the warm, gripping walls of his passage molding instantly to your anatomy. The stallion throws his head back, his cyan-frosted hair tumbling over his dark shoulders as a melodious, shivering moan tears from his throat. He is a masterpiece of submissive compliance, his body practically melting backward to take every inch of your length.";
	say "     Establishing a steady, demanding pace, you begin to hammer your hips against his firm rear, driving yourself deep into his gripping hole. Each heavy plunge causes his slender frame to shudder against the wall, the impact sending ripples through his dark, velvety fur. The visual contrast is striking - his masculine equine features and massive, dangling cock juxtaposed against the dainty black silk gloves gripping the plaster and the sheer stockings clinging to his legs. 'Yes, just like that, stretch me out!' he pants, his voice dripping with a sultry, practiced cadence. You reach around to grab his hips, anchoring him securely as you increase the speed of your thrusts, the friction generating a profound, building heat between your colliding bodies.";
	WaitLineBreak;
	say "     The wet, rhythmic slapping of skin against fur fills the corridor, a chaotic symphony of lust that drives the tension in your groin to a fever pitch. Your submissive partner is completely lost in the roleplay, his long tail wrapping loosely around your thigh as his internal muscles clench in frantic, uncoordinated waves. He begs for his Daddy to use him, his breathy cries echoing off the wall while his enormous equine member pulses violently in the empty air before him. The feeling of his tight ass milking your shaft is incredible, a crushing pressure that threatens to pull the very soul from your body. Leaning in close, you whisper a string of dirty, praising commands into his leaf-shaped ear, fueling his arousal until he is shivering on the absolute brink of his peak.";
	say "     A heavy surge of heat signals the end as your climax breaks, your hips snapping forward to bury yourself to the absolute hilt. You let out a guttural groan, pumping a thick, voluminous torrent of hot seed straight into his deepest recesses. The sudden flooding of his core triggers his own catastrophic release, his massive equine cock erupting in a heavy, pulsing fountain. A surprisingly large amount of thick, creamy fluid blast against the wall in front of him, splashing back to coat his slender chest and thighs in a glistening, musky deluge. You remain locked inside him for a long moment, savoring the tight, twitching pulses of his internal grip. With a firm tug, you pull your softening cock free, your white cream spilling from his abused entrance to run down his dark, stocking-clad legs.";
	WaitLineBreak;
	say "     Panting softly, the stallion leans against the cream-splattered wall, his long, dark tail twitching as he catches his breath. He slowly turns his head, peering over his shoulder with half-lidded green eyes that sparkle with a deeply satisfied mischief. 'I promise, sir, I've learned my lesson,' he purrs, his voice returning to that delicate, breathy pitch, though a sly, unapologetic smirk tugs at the corner of his equine muzzle. 'I'll be a very good, obedient pet from now on.' His tone is a perfect, theatrical pout, a performance designed entirely for your benefit. The way he shifts his weight, drawing attention to his ruined stockings and the slick, white mess running down his thighs, is an open invitation for future discipline.";
	say "     You let out a low chuckle, fully understanding the game he's playing. Delivering one final, light swat to his sticky rear, you give him a firm push to send him on his way. You reply that he better be a sweet happy slut from now on, playing along with his established dynamic. He adjusts his pale blue thong with a dramatic sigh, giving you one last, lingering, slutty grin before prancing down the hallway, the click of his hooves echoing in the quiet corridor. Watching his slender, furred hips sway as he retreats, you have absolutely no doubt that if you cross paths again, he will be just as bratty, teasing, and desperate for a firm hand. And as you adjust your own clothes, you have to admit that the prospect of putting him in his place a second time is incredibly hot.";
	CreatureSexAftermath "Stallionboi" receives "AssFuck" from "Player";

to say Stallionboi_ride_anal:
	say "     Grabbing the black leather collar around his neck, you apply a firm downward pressure that forces the stallion to his knees, before easily pushing him over onto his back. He hits the floor with a soft thud, his sheer black stockings contrasting starkly against his dark chocolate fur as his digitigrade legs sprawl open. As you step over him and [if Player is not naked]strip away your lower garments to [end if]reveal your own male anatomy, a sly, thoroughly satisfied smirk spreads across his feminine muzzle. 'Mmm, now we're talking,' he purrs, his voice dripping with a breathy, performative arrogance. His hands move to the pale blue silk of his thong, pulling the skimpy fabric aside to completely free his massive, dark equine manhood, which springs upright and begins to weep copious amounts of clear pre-cum.";
	say "     Ignoring his strutting tone, you reach down and gather a handful of the slick, pre-cum dripping from his flared crown, using it to thoroughly prep your own tight entrance. The stallion watches your meticulous preparation with a smug, heavy-lidded gaze, clearly believing he has successfully manipulated the encounter to serve his own dominant fantasy. He shifts his hips, presenting the thick, foot-long pillar of meat with a cocky tilt of his head. He expects you to eagerly impale yourself, waiting for the moment you surrender to the overwhelming size of his weapon. Instead of mounting him, however, your hand shoots past his throbbing shaft, your fingers closing in a sudden, vice-like grip around the heavy, lap-filling mass of his testicles.";
	WaitLineBreak;
	say "     You apply a sharp, calculated squeeze to the sensitive flesh - hard enough to sting a bit, sending a jolt of shocking discomfort to put him in his place. The arrogant smirk vanishes from his face instantly, replaced by a wide-eyed look of sudden panic as he gasps, his entire body going rigid against the floor. Leaning in close, you deliver a low, quiet threat, making it abundantly clear that if he doesn't drop the bratty attitude immediately, you will walk away right now, leaving him stretched out on the floor, aching, leaking, and completely unfulfilled. The reality of your dominance hits him like a physical weight, shattering the illusion of control he thought he held over the situation.";
	say "     The transformation is instantaneous. The performative swagger melts away, leaving a genuinely flustered, desperate submissive in its wake. 'Wait! No, please, sir, I'm sorry!' he babbles, his voice cracking slightly as his leaf-shaped ears pin flat against his skull. He reaches out with trembling, black-gloved hands, not to push you away, but to grasp your wrists in a pleading gesture. 'I'll be good, I swear! Just... please don't leave me like this. It aches so much. I want you to use it, please.' The sight of the previously boastful femboy now begging for your touch is intensely satisfying, proving that underneath the silk and the attitude, he is desperate for a firm hand to put him in his place.";
	WaitLineBreak;
	say "     Accepting his surrender, you release his testicles and finally lower your greased entrance over the blunt, wet head of his cock. A loud, wet pop echoes as you breach your own ring of muscle, the sheer girth of his flared crown forcing your anatomy to stretch wide. You let out a ragged groan, sinking your nails into his furred shoulders for balance as you take the formidable invasion inch by relentless inch. The stallion whimpers beneath you, his eyes rolled back in a daze of sheer, overwhelming pleasure as he feels his heavy shaft disappear into your tight, hot core. His dark, velvety fur shivers beneath your knees, his long tail thrashing wildly against the floor as you finally bottom out, burying his immense length to the hilt.";
	say "     Establishing a deep, commanding rhythm, you begin to ride his massive pillar, using your weight to force him deep inside with every downward plunge. The internal friction is incredible, your tight passage milking the thick, solid meat of his shaft as you bounce against his pelvis. The stallion is completely overwhelmed by the sensation of being sheathed in your gripping hole, his head tossing side to side as a chaotic symphony of moans and breathy cries escapes his lips. 'Oh god, yes, it's so tight,' he pants, his black-gloved hands reaching up to weakly grasp your hips, no longer trying to control the pace but simply holding on for the ride. His initial reluctance has entirely vanished, replaced by a dazed, hyper-aroused submission as he thrusts his hips upward, eager to meet your demanding pace.";
	WaitLineBreak;
	say "     The blistering friction and the profound stretch of your passage rapidly propel the tension in your groin toward a devastating peak. You quicken your movements into a frantic blur, your breath coming in ragged, guttural moans that echo off the walls. The stallion beneath you is a vision of frantic compliance, his entire body shuddering with the internal hum of his impending release as the pressure in his massive cock reaches a fever pitch. He begs you to take it all, his voice a breathless, high-pitched whine as his lap-filling testicles churn violently against his dark thighs. Squeezing your eyes shut, your own climax crests, your rigid shaft firing thick, pulsing ropes of seed that splatter across his furred chest and his feminine muzzle, your internal muscles clenching in violent, rhythmic spasms around his invading girth.";
	say "     Your internal contractions trigger his own catastrophic release, his massive equine cock pulsing furiously as he unloads a heavy, voluminous torrent of seed straight into your deepest recesses. A large gush of thick, creamy fluid blast against your internal walls, the immense pressure and volume creating an intoxicating sensation of profound, heavy fullness. He roars in euphoric ecstasy, his body locking into a rigid arc as he pumps every last drop of his payload into your core. When you finally lift yourself off with a loud, wet pop, a heavy deluge of his white seed spills from your entrance, splashing over his chest. Panting softly, the stallion peers up at you with half-lidded green eyes, a sly, unapologetic smirk tugging at his muzzle despite his ruined state. 'I promise, sir, I'll be a very good boy from now on,' he purrs, the familiar, theatrical pout returning to his voice. You both know it's a lie, but as you [if Player is not naked]adjust your clothes and [end if]step away, you have to admit that the prospect of putting the brat in his place a second time is incredibly hot.";
	CreatureSexAftermath "Player" receives "AssFuck" from "Stallionboi";

to Stallionboi_oral_pussy:
	project the Figure of Stallionboi_hard_icon;
	say "     Grabbing the black leather collar around his neck, you apply a firm downward pressure that immediately halts his teasing bravado. The stallion sinks to his knees, his dark chocolate fur contrasting sharply against the floor as his digitigrade legs, clad in their sheer black stockings, tuck neatly beneath his slender frame. As you step forward and [if Player is not naked]strip away your lower garments to reveal [else]push forward [end if]a slick, glistening vulva, his green eyes go wide with sudden confusion. 'Wait, I'm not really into-' he begins, his voice losing its breathy, performative pitch for a moment of genuine hesitation. You cut his protest short, stepping into his space and firmly pressing your drenched folds directly against his half-equine muzzle. The shock of the hot, wet contact silences him instantly, his leaf-shaped ears pinning back as the pungent, musky scent of your arousal floods his senses.";
	say "     Whatever reservations he had evaporate the second you grind your clit against his lips, the sheer dominance of the act overriding his initial hesitation. His innate submissive programming takes over, his mouth parting instinctively to accept the heavy, wet pressure of your sex. He lets out a muffled, surprised hum as your slickness coats his chin, his long, prehensile tongue tentatively darting out to taste your feminine nectar. The flavor is a sudden revelation to him, and you feel the rough, textured surface of his tongue begin to lap at your folds with a growing, eager rhythm. Despite his earlier protest, his massive equine manhood - unable to be contained by the skimpy blue pouch - throbs heavily against his stomach, leaking a thick trail of pre-cum onto the floor as he submits to your command.";
	WaitLineBreak;
	say "     Taking a firm grip on the blue-frosted tips of his hair, you dictate the pace, rocking your hips against his face to ensure he services you exactly how you demand. The stallion proves to be an incredibly fast learner, his long muzzle providing a broad, warm surface to rub against. He uses the dexterity of his tongue to part your lips and swirl around your clit, a wet, slurping sound echoing in the quiet space with every pass. He is a masterpiece of eager compliance, his hands reaching down to stroke his own massive, leaking cock while he buries his face in your wetness. The feeling of his slick tongue and warm breath against your sensitive nerves is intoxicating, sending electric shudders down your spine as you force him to drink deep of his new obsession.";
	say "     The relentless, focused stimulation pushes you rapidly over the edge into a devastating, toe-curling climax. You cry out, your vaginal walls clenching in violent, rhythmic spasms as a heavy flood of clear, feminine fluid gushes from your depths, soaking his muzzle and face. The sheer intensity of your release triggers his own catastrophic peak; his hand pumps his massive equine cock in a blur, sending heavy, splashing ropes of creamy seed cascading onto the floor beneath him. The stallion greedily laps up every drop of your gushing nectar, swallowing thickly as you ride out the final, twitching tremors against his face. When you finally step back, adjusting your clothes with a sated sigh, the panting femboy remains kneeling in the sticky puddle of his own making, his chin dripping with your slickness as a thoroughly dazed, hungry grin stretches across his face.";
	CreatureSexAftermath "Stallionboi" receives "OralPussy" from "Player";

to Stallionboi_ride_pussy:
	project the Figure of Stallionboi_hard_icon;
	say "     Taking a firm grip on the black leather of his collar, you give a sharp tug that easily unbalances the slender stallion, sending him tumbling onto his back. He hits the floor with a soft thud, his sheer black stockings contrasting starkly against his dark chocolate fur as his digitigrade legs sprawl open. A moment of genuine confusion flashes across his green eyes as you stand over him and [if Player is not naked]strip away your lower garments, revealing [else]reveal [end if]a slick, swollen vulva. 'Wait, hold on, I'm not really into-' he stammers, his breathy, performative tone faltering in the face of your unexpected anatomy. You quickly cut him off with a sharp, commanding gesture, instructing him to shut his mouth and simply act as the obedient fucktoy he was designed to be. The authoritative tone hits him like a physical blow, his leaf-shaped ears pinning back as his submissive instincts immediately override his hesitation.";
	say "     Sinking into his role, the stallion obliges with a flushed, eager nod. His hands move to the pale blue silk of his thong, pulling the skimpy fabric aside to completely free his massive equine manhood. It springs upward, a thick, dark pillar that easily measures over a foot in length, the flared, mushroom-like head already weeping copious amounts of clear pre-cum. Following your silent command, he grips the base of his shaft with both dainty, black-gloved hands, holding the heavy meat perfectly straight and steady for your use. He looks up at you through long, feminine lashes, his chest heaving with rapid breaths. 'Yes, ma'am,' he whispers, his voice trembling with a mixture of apprehension and a sudden, undeniable surge of arousal. 'Use it however you want.'";
	WaitLineBreak;
	say "     Stepping carefully over his sprawling form, you align your drenched, aching folds directly over the blunt, wet crown of his cock and begin a slow, deliberate descent. The initial breach is a staggering sensation, the sheer girth of his flared head forcing your tight passage to stretch wide. You let out a ragged gasp, sinking your nails into his shoulders for balance as you take the formidable invasion inch by relentless inch. The stallion whimpers beneath you, his eyes going wide as he feels his heavy shaft disappear into a wet, hot heat he hasn't experienced before. His dark, velvety fur shivers beneath your knees, his long tail thrashing wildly against the floor as you finally bottom out, burying his immense length to the hilt within your depths.";
	say "     Establishing a deep, commanding rhythm, you begin to ride his massive pillar, using your weight to force him deep inside with every downward plunge. The internal friction is incredible, the ribbed walls of your canal milking the thick, solid meat of his shaft as you bounce against his pelvis. The stallion is completely overwhelmed by the novel sensation of being sheathed in feminine anatomy, his head tossing side to side as a chaotic symphony of moans and breathy cries escapes his lips. 'Oh god, it's so tight,' he pants, his black-gloved hands reaching up to weakly grasp your hips. 'I didn't know... I didn't know it could feel like this!' His initial reluctance has entirely vanished, replaced by a dazed, hyper-aroused submission as he thrusts his hips upward, eager to meet your demanding pace.";
	WaitLineBreak;
	say "     The blistering friction and the profound stretch of your passage rapidly propel the tension in your groin toward a devastating peak. You quicken your movements into a frantic blur, your breath coming in ragged, guttural moans that echo off the walls. The stallion beneath you is a vision of frantic compliance, his entire body shuddering with the internal hum of his impending release as the pressure in his massive cock reaches a fever pitch. He begs you to take it all, his voice a breathless, high-pitched whine as his lap-filling testicles churn violently against his dark thighs. Squeezing your eyes shut, your orgasm hits you in a wave of blinding heat, your vaginal walls clenching in violent, rhythmic spasms around his invading girth.";
	say "     Your internal contractions trigger his own catastrophic release, his massive equine cock pulsing furiously as he unloads a heavy, voluminous torrent of seed straight into your deepest recesses. A flood of thick, creamy fluid blast into your womb, the immense pressure and volume flooding your depths and creating an intoxicating sensation of profound, heavy fullness. He roars in euphoric ecstasy, his body locking into a rigid arc as he pumps every last drop of his payload into your gripping pussy. You remain seated on his shaft for a long moment, panting heavily as you savor the final, twitching pulses of his member. When you finally lift yourself off, a loud, wet pop echoes in the silence, followed immediately by a heavy, splashing deluge of his white seed and your slick nectar spilling from your entrance. The thick cream rains down onto his chest and stomach, leaving the dazed, panting stallionboi covered in the glistening evidence of your dominance as you [if Player is not naked]adjust your clothes and [end if]step away.";
	CreatureSexAftermath "Player" receives "PussyFuck" from "Stallionboi";

to Stallionboi_spank_deny:
	project the Figure of Stallionboi_hard_icon;
	say "     Catching the slender hybrid by his silk-clad waist before he can scramble away, you spin him around and bend him firmly over the nearest surface. The sudden shift in momentum completely shatters his haughty facade, leaving him squirming indignantly as his dark equine tail swishes in frantic circles. His black thigh-high stockings stretch taut over lithe legs while his hooves tap nervously against the floor, failing to find leverage. Looking down at the exposed curve of his rear, barely covered by his skimpy thong, you take a firm hold of his hip to keep him planted. An indignant squeak escapes his tapered muzzle as he glances over his shoulder, green eyes flashing with an uneasy mixture of mortification and excitement. For all his earlier bluster, the defeated stallionboi offers zero genuine resistance, his body yielding completely to your grip.";
	say "     Raising an open palm, you bring it down with a crisp, measured smack against the soft curve of his haunches. The stinging pop echoes through the room, earning a breathy yelp that sounds remarkably delicate coming from an equine throat. You follow it with another brisk swat to the opposite cheek, the impact sending a shudder through his spine and warming the skin beneath his dark coat. Rather than backing down, the rhythm of light discipline clearly goes straight to his head. His breath hitches into soft, needy pants, his ears pinning back in surrender while his rigid length twitches frantically within the stretched fabric of his pouch. With every playful tap, his hips give a tiny, helpless twitch, clearly aroused by the firm contact even as his long tail attempts to flick in flustered embarrassment.";
	WaitLineBreak;
	say "     Resting your hand firmly on his lower back to halt his squirming, you calmly inform the flustered hybrid that bossy brats who pick fights do not get rewarded with a release. You make it clear that if he wants someone to take care of that desperate ache, he needs to learn some manners and act sweet instead of throwing cheap shots. The realization crashes over him like a bucket of ice water, his posture stiffening before melting into immediate, frantic desperation. 'Wait, no! You can't be serious, sweetie!' he wails, twisting his neck around to stare up at you with wide, pleading eyes. 'You got me all worked up! You can't just smack my ass red and walk away! Please, just a little touch... I'll behave, I swear I will!' His hooves stomp anxiously against the tile, his hips rolling in a futile bid to coax your hands toward his swollen front.";
	say "     Refusing to yield to his dramatic begging, you haul him upright by his shoulders, casually patting his cheek and smoothing down the cyan tips of his disheveled mane. Giving his stung rear one last dismissive swat, you step back and point toward the hallway, telling him his time is up and that he will just have to sleep off his frustration. The defeated stallion lets out a petulant, frustrated whine, his cheeks burning with an intense blush as he crosses his long, silk-gloved arms over his bare chest. 'Ugh, you are the absolute worst!' he huffs, stomping a clopped hoof against the floor with theatrical indignation. Tail lashing in irritated circles, he gathers whatever shred of dignity he has left and stalks down the corridor, thighs rubbing uncomfortably around his unrelieved erection as he carries his lesson with him into the dark.";
	CreatureSexAftermath "Stallionboi" receives "Spanking" from "Player";

Section 2 - Creature Insertion

to say Stallionboi_Desc:
	say "     Wandering through the building you encounter a horny stallionboi. You see that he is wearing black silk stockings and a skimpy tight black thong that isn't hiding his fully equine manhood. His look is finished off with long black silk gloves and black choker collar around his neck. The stallionboi has a slender almost girlish figure. His human body is starting to sprout dark chocolate colored fur, a long black horsetail flicks eagerly behind him. His face is stretched out into a slender, feminine half equine muzzle and his ears are more equine than human. His dark hair is shoulder length with bright blue frosted tips. Giving you a slutty grin, he strides towards you and says, 'You are going to look so hot when I get done with you!'";

Table of CombatPrep (continued)
name(text)	PrepFunction(text)
"Stallionboi"	"[PrepCombat_Stallionboi]"

to say PrepCombat_Stallionboi:
	project the Figure of Stallionboi_clothed_icon;
	setmongender 3;

Table of Random Critters (continued)
NewTypeInfection (truth state)	Species Name	Name	Enemy Title	Enemy Name	Enemy Type	Attack	Defeated	Victory	Desc	Face	Body	Skin	Tail	Cock	Face Change	Body Change	Skin Change	Ass Change	Cock Change	str	dex	sta	per	int	cha	sex	HP	lev	wdam	area	Cock Count	Cock Length	Ball Size	Nipple Count	Breast Size	Male Breast Size	Cunt Count	Cunt Depth	Cunt Tightness	SeductionImmune	Libido	Loot	Lootchance	TrophyFunction	MilkItem	CumItem	Scale (number)	Body Descriptor (text)	Type (text)	Magic (truth state)	Resbypass (truth state)	non-infectious (truth state)	Cross-Infection (text)	DayCycle	Altcombat (text)	BannedStatus (truth state)
--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--;

When Play begins:
	Choose a blank row from Table of Random Critters;
	now NewTypeInfection entry is false;
	now Species Name entry is "Horse"; [ Name of the overall species of the infection, used so a "male x" and "female x" have "pureblood X" children. ]
	add "Stallionboi" to infections of EquineList;
	add "Stallionboi" to infections of FurryList;
	add "Stallionboi" to infections of NatureList;
	add "Stallionboi" to infections of MaleList;
	add "Stallionboi" to infections of BluntCockList;
	add "Stallionboi" to infections of SheathedCockList;
	add "Stallionboi" to infections of BipedalList;
	add "Stallionboi" to infections of TailList;
	now Name entry is "Stallionboi";
	now enemy title entry is ""; [ Name of the encountered creature at combat start - Example: "You run into a giant collie." instead of using "Smooth Collie Shemale" infection name. ]
	now enemy Name entry is ""; [ Specific name of unique enemy. ]
	now enemy type entry is 0; [ 0 = non unique enemy; 1 = unique (unknown name); 2 = unique (known name) | Used to disqualify unique enemies from Vore/UB and showing the enemy name in encounters. ]
	now attack entry is "[one of]He gives you an equine grin for a minute, confusing you slightly, as he slowly stretches and poses teasingly in front of you, your body growing hot and aroused from the sexy show[or]The stallionboi reaches out and strokes his hands over your body teasingly[or]Pulling a large transparent blue double ended dildo from somewhere, he smacks you in the ass with it[at random].";
	now defeated entry is "[Stallionboi loses]";
	now victory entry is "[Stallionboi wins]";
	now desc entry is "[Stallionboi_Desc]"; [ Description of the creature when you encounter it.]
	now face entry is "slight equine muzzle, its slender stretched out look is strangely sexy as your stare out of it with your sensuous equine eyes. Your mostly equine ears sticking up jauntily out of your long sexy mane of dark brown hair with sea green highlights, giving a rather sexy and teasing look overall to your new face"; [ Face description, format as "Your face is [Face of Player]." ]
	now body entry is "slender and feminine, clothed in some sexy slutty clothes you found near where you finished changing, your sexy silk stalkings and gloves, do nothing to hide your slightly equine changes, though the feel of their dark purple silk against your [Skin of Player] skin makes you feel increasingly aroused and sexy with every step";
	now skin entry is "[one of]soft feminine[or]lightly furred[or]sexy chocolate furred[at random]";
	now tail entry is "You have a long, sexy equine tail swishing behind you eagerly, swaying side to side with every step as if inviting some sexy beast to hold you down and fuck you."; [ Tail description, write a whole Sentence or leave blank. ]
	now cock entry is "[one of]equine[or]stallion like[or]thick[or]blunt equine[at random]";
	now face change entry is "it begins to stretch and change, pushing forward slightly and giving you a more equine look, even as your hair grows out and changes in color and texture to form a proper mane, you find yourself neighing and squealing with pleasure as your face finishes shifting, and your ears come to rest on top of your head, and you find you love admiring your new sexy look, and your lovely dark mane with shimmering sea green highlights threaded through it"; [ Face change text, format as "Your face feels funny as [face change entry]." ]
	now body change entry is "it shifts and changes, your bones shifting slightly as your body curves into a more suggestive feminine shape, and your hips widen slightly even as a strange erotic energy seems to run through you, making you shudder with arousal as a soft breeze brushes your body. Looking around desperately, you spot a discarded bit of silk clothing nearby, and quickly pull it on, the sleek silk stockings and gloves doing nothing to hide your sexy new form, though the rich royal purple silk looks amazing on you, and the feel of the silk caressing your body teasingly makes you moan with pleasure"; [ Body change text, format as "Your body feels funny as [body change entry]." ]
	now skin change entry is "it shudders and softens, becoming sexier and more feminine, before a small coating of sexy dark brown fur begins to grow in, the fur only covering part of your body in its sexy sleekness, and leaving the rest of your chest and other areas teasingly bare";
	now ass change entry is "a sexy little equine tail begins to form behind you, the new equine appendage making you moan with pleasure as it swishes behind you, somehow every movement of your new appendage seeming amazingly erotic, especially when its soft silken strands brush up against your tight and eager ass";
	now cock change entry is "it balloons outwards, your balls swelling up as they begin to hang even lower between your legs. Your large thick new cock darkening in color as its textures changes, and the tip flattens out until you have a properly shaped equine shaft hanging low between your legs"; [ cock change text. format as "Your cock feels funny as (your text)." ]
	now str entry is 20;
	now dex entry is 14;
	now sta entry is 18;
	now per entry is 12;
	now int entry is 12;
	now cha entry is 14;
	now sex entry is "Male"; [ Defines which sex the infection will try and make you. current options are 'Male' 'Female' 'Both']
	now HP entry is 25;
	now lev entry is 3; [ Level of the Monster, you get this much HP if you win, or this much HP halved if you loose ]
	now wdam entry is 3; [ Amount of Damage monster Does when attacking. ]
	now area entry is "Stable"; [ Current options are 'Outside' and 'Mall'. Case sensitive]
	now Cock Count entry is 1; [ How many cocks will the infection try and cause if sex is 'Male' or 'Both']
	now Cock Length entry is 15; [ Length infection will make cock grow to if cocks]
	now Ball Size entry is 3; [ Size of balls 1-7: "acorn-sized", "dove egg-sized", "chicken egg-sized" "goose-egg sized", "ostrich-egg sized", "basketball-sized", "beachball-sized"]
	now Nipple Count entry is 0; [ Number of nipples infection will give you (males have nipples too) ]
	now Breast Size entry is 0; [Size of breasts infection will try to attain ]
	now Male Breast Size entry is 0; [ Breast size for if Sex="Male", usually zero. ]
	now Cunt Count entry is 0; [ if sex = "Female or both", indicates the number of female sexes infection will grant you.]
	now Cunt Depth entry is 0; [penetrable length in inches; some minor stretching allowed, or more with Twisted Capacity] [ Length of female sex infection will attempt to give you. ]
	now Cunt Tightness entry is 0; [size 1-5, generates adjectives of extremely tight/tight/receptive/open/gaping] [ Width of female sex infection will try and give you ]
	now SeductionImmune entry is false;
	now libido entry is 75; [ As part of infection, the Player will be gradually moved towards this value; also used for the creature's seduce defense as a penalty ]
	now loot entry is "lucky horseshoe"; [ Loot monster drops, usually infective with the monster's _own_ strain (for example if there is a Cross-Infection from sex)]
	now lootchance entry is 20; [ Chance of loot dropping 0-100 ]
	now MilkItem entry is "stallionboi milk"; [ Item to be given to the player if they have this infection and milk themselves. ]
	now CumItem entry is ""; [ Item to be given to the player if they have this infection and jerk off. ]
	now TrophyFunction entry is "-"; [ Function to generate a list of optional loot items, of which the player can choose one after victory. ]
	now scale entry is 3; [ Number 1-5, approx size/height of infected PC body: 1=tiny, 3=avg, 5=huge ]
	now body descriptor entry is "[one of]girly[or]feminine[at random]";
	now type entry is "[one of]equine[or]horse-like[at random]";
	now magic entry is false;
	now resbypass entry is false;
	now non-infectious entry is false;
	now Cross-Infection entry is ""; [ Infection that this infection will give the player when they lose; can be left empty if they infect with the monster's own strain. ]
	now DayCycle entry is 0; [ 0 = Up at all times; 1 = Diurnal (day encounters only); 2 = Nocturnal (night encounters only);]
	now altcombat entry is "default";
	now BannedStatus entry is false;

[
Table of New Infection Parts (continued)
Species Name	Name	Body Weight	Body Definition	Androginity	Head Change	Head Description	Head Adjective	Head Skin Adjective	Head Color	Head Adornments	Hair Length	Hair Shape	Hair Color	Hair Style	Beard Style	Body Hair Length	Eye Color	Eye Adjective	Mouth Length	Mouth Circumference	Tongue Adjective	Tongue Color	Tongue Length	Torso Change	Torso Description	Torso Adjective	Torso Skin Adjective	Torso Adornments	Torso Color	Torso Pattern	Breast Adjective	Breast Size	Male Breast Size	Nipple Count	Nipple Color	Nipple Shape	Back Change	Back Adornments	Back Skin Adjective	Back Color	Arms Change	Arms Description	Arms Skin Adjective	Arms Color	Locomotion	Legs Change	Legs Description	Legs Skin Adjective	Legs Color	Ass Change	Ass Description	Ass Skin Adjective	Ass Color	Ass Width	Tail Change	Tail Description	tail skin adjective	Tail Color	Asshole Depth	Asshole Tightness	Asshole Color	Cock Change	Cock Description	Cock Adjective	Cock Color	Cock Count	Cock Girth	Cock Length	Ball Description	Ball Count	Ball Size	Cunt Change	Cunt Description	Cunt Adjective	Cunt Color	Cunt Count	Cunt Depth	Cunt Tightness	Clit Size
--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--;

When Play begins:
	Choose a blank row from Table of New Infection Parts;
	now Species Name entry is ""; [ Name of the overall species of the infection, used so a "male x" and "female x" have "pureblood X" children. ]
	now Name entry is ""; [matching infection name to Table of Random Critters]
	now Body Weight entry is 5; [scale of 1-9 for body weight, grouped into low weight (1-3), mid weight (4-6) and high weight (7-9)]
	now Body Definition entry is 5; [scale of 1-9 for body definition, grouped into low muscle (1-3), mid muscle (4-6), high muscle (7-9)]
	[Body Adjective is generated out of the body weight and body definition and can be used in scenes - one word descriptive adjective depending on weight and definition groups: low weight group: skinny/slender/lithe; mid weight group: average/fit/muscled; high weight group: pudgy/husky/jacked]
	now Androginity entry is 5; [1-9 scale of hypermasculine to hyperfeminine]
	[Gender Adjective is generated out of androginity 1-9: hypermasculine/masculine/effeminate/somewhat effeminate/androgynous/feminine butch/tomboyish/feminine/hyperfeminine]
	now Head Change entry is ""; [partial sentence that fits in: "Your head and face [one of]tingle[or]go flush[or]vibrate with odd pleasure[or]go cold[or]feel oily[at random] as [head change entry]."]
	now Head Description entry is ""; [partial sentence that fits in "Your face and head resemble that of [Head Description of Player]. You have [Eye Adjective of Player], [Eye Color of Player] eyes and an overall [Gender Adjective of Player] appearance."]
	now Head Adjective entry is ""; [one word descriptive adjective (avian/canine/...)]
	now Head Skin Adjective entry is ""; [one word descriptive adjective]
	now Head Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Head Adornments entry is "";[partial sentence that fits in "Before moving on from your head, you give your [Head Adornments of Player] a proud glance followed by a light caress."]
	now Hair Length entry is 2; [hair length in inches]
	now Hair Shape entry is ""; [one word shape descriptor (curly/straight/...)]
	now Hair Color entry is ""; [one word color descriptor]
	now Hair Style entry is ""; [one word style descriptor (ponytail/mohawk/buzzcut/...) to fit "On top of your head you have [Hair Length of Player] inch long, [Hair Shape of Player] [Hair Color of Player] hair in the [Hair Style of Player] style."]
	now Beard Style entry is ""; [short beard style (goatee/3-day stubble beard/porn stache/mutton chops beard/...) to go into "You have a [Hair Color of Player] [Beard Style of Player]."]
	now Body Hair Length entry is 0; [numerical value, 0-4 (no body hair/light/moderate/heavy/furry) - only set to > 0 if the infection does not have fur/scales/etc. !]
	now Eye Color entry is ""; [one word color descriptor]
	now Eye Adjective entry is ""; [one word descriptive adjective (slitted/round/...)]
	now Mouth Length entry is 3; [inches deep for face fucking; maximum possible will be double this number (when deep throating)]
	[Mouth Length Adjective is generated by a function and can be used in scenes too - "petite, shallow, average, deep, bottomless"]
	now Mouth Circumference entry is 3; [mouth circumference 1-5, see Mouth Circumference Adjective]
	[Mouth Circumference Adjective is generated by a function and can be used in scenes too - "tiny, small, normal, wide, gaping"]
	now Tongue Adjective entry is ""; [one word descriptive adjective (wide/slobbery/...)]
	now Tongue Color entry is ""; [one word color descriptor]
	now Tongue Length entry is 3; [length in inches]
	now Torso Change entry is ""; [partial sentence that fits in: "Your torso [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Torso Change entry]."]
	now Torso Description entry is ""; [partial sentence, fitting in "Looking down at yourself, you appear [Gender Adjective of Player] with a [Body Adjective of Player] build. Your torso is [Torso Description of Player][if Body Hair Length of Player > 1], covered in [Torso Color of Player] skin and [Body Hair Description of Player][else if Body Hair Length of Player is 1], covered in smooth, [Torso Color of Player] skin[end if]."]
	now Torso Adjective entry is ""; [one word descriptive adjective (avian/canine/...)]
	now Torso Adornments entry is ""; [(pouch/udders/...); partial sentence to fit: "You take a moment to feel your [Torso Adornments of Player]."]
	now Torso Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Torso Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Torso Pattern entry is ""; [single word color adjective for the dominant pattern of the skin/fur/feathers/scales]
	now Breast Adjective entry is ""; [adjective(s) example: round, pointy, perky, saggy, bouncy. This would serve as either a general appearance of a infections breasts or possibly something that may be effected by a item or NPC.]
	now Breast Size entry is 0; [cup size as number, counting Flat Pecs = 0, A = 1, B = 2, ...]
	now Male Breast Size entry is 0; [cup size as number, counting Flat Pecs = 0, A = 1, B = 2, ...]
	now Nipple Count entry is 2; [count of nipples]
	now Nipple Color entry is ""; [one word color descriptor]
	now Nipple Shape entry is ""; [shape example: any shape will do as long as it has a baseline with a current infection or item]
	now Back Change entry is ""; [partial sentence that fits in: "Your back [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Back Change entry]."]
	now Back Adornments entry is ""; [partial sentence to fit: "Your back tickles with the feeling of movement caused by [back adornments of Player]."]
	now Back Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Back Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	[Limbs Adjective is generated by a function and can be used in scenes too - "rail-thin, slender, sinewy, average, firm, muscular, flabby, meaty, rippling"]
	now Arms Change entry is ""; [partial sentence that fits in: "Your arms [one of]tingle[or]go flush[or]vibrate with odd pleasure[or]go cold[or]feel oily[at random] as [Arms Change entry]."]
	now Arms Description entry is ""; [partial sentence to fit: "Your [Limbs Adjective of Player] arms are [Arms Description of Player]."]
	now Arms Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Arms Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Locomotion entry is ""; [one word adjective: (bipedal/quadrupedal/octapedal/serpentine/sliding)]
	now Legs Change entry is ""; [partial sentence that fits in: "Your legs [one of]tingle[or]go flush[or]vibrate with odd pleasure[or]go cold[or]feel oily[at random] as [Legs Change entry]."]
	now Legs Description entry is ""; [partial sentence to fit: "As your inspection goes even lower, you come to the two [Body Adjective of Player] legs supporting you. They are [Legs Description of Player]."]
	now Legs Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Legs Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Ass Change entry is ""; [partial sentence that fits in: "Your ass [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Ass Change entry]."]
	now Ass Description entry is ""; [partial sentence to fit: "Using your hands you feel your behind enjoying the sensation of your [Ass Width Adjective of Player], [Ass Shape Adjective of Player] [Ass Description of Player]." (For players with skin, instead of the period: ", covered in [Ass Color of Player] skin and [Body Hair Description of Player]"]
	now Ass Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Ass Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Ass Width entry is 3; [ass width from 1-5]
	[Ass Width Adjective generated by function out of ass width: dainty/small/round/huge/enormous]
	[Ass Adjective generated by function out of body definition and ass width]
	now Tail Change entry is ""; [partial sentence that fits in: "Your rear [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [if HasTail of Player is true]your existing tail is changed into a [Tail Description entry][else][Tail Change entry][end if]."]
	now Tail Description entry is ""; [partial sentence to fit: "Just below your lower back sprouts a [Tail Description of Player], which you move back and forth with glee."]
	now Tail Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Tail Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Asshole Depth entry is 7; [inches deep for anal fucking]
	[Asshole Depth Adjective is generated by a function and can be used in scenes too - "petite (< 3), shallow (< 5), average (< 9), deep (< 15), bottomless (15+)"]
	now Asshole Tightness entry is 3; [asshole tightness 1-5, "extremely tight, tight, receptive, open, gaping"]
	[Asshole Tightness Adjective is generated by a function and can be used in scenes too - "extremely tight, tight, receptive, open, gaping"]
	now Asshole Color entry is ""; [one word color descriptor]
	now Cock Count entry is 0;
	now Cock Girth entry is 0; [thickness 1-5, generates the Cock Girth Adjective]
	[Cock Girth Adjective is generated by a function and can be used in scenes too: thin/slender/average/thick/monstrous]
	now Cock Length entry is 0; [length in inches]
	now Cock Adjective entry is ""; [one word adjective: avian/canine/...]
	now Cock Change entry is ""; [partial sentence that fits in: "Your cock [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Cock Change entry]."]
	now Cock Description entry is ""; [partial sentence to fit: "You have a [Cock Girth Adjective of Player], [Cock Length of Player]-inch-long [Cock Adjective of Player] [one of]cock[or]penis[or]shaft[or]maleness[at random] that [cock Description of Player]."]
	now Cock Color entry is ""; [one word color descriptor]
	now Ball Count entry is 0; [allowed numbers: 1 (uniball), 2 or 4]
	now Ball Size entry is 0; [size of balls 1-7: "acorn-sized", "dove egg-sized", "chicken egg-sized" "goose-egg sized", "ostrich-egg sized", "basketball-sized", "beachball-sized"]
	[Ball Size Adjective is generated by a function and can be used in scenes too]
	now Ball Description entry is ""; [partial sentence to fit: "Underneath it hangs a pair of [Ball Size Adjective of Player] [Ball Description of Player]."]
	now Cunt Count entry is 0;
	now Cunt Depth entry is 0; [penetrable length in inches; some minor stretching allowed, or more with Twisted Capacity]
	now Cunt Tightness entry is 0; [size 1-5, generates adjectives of extremely tight/tight/receptive/open/gaping]
	[Cunt Tightness Adjective is generated by a function and can be used in scenes too: extremely tight/tight/well-used/open/gaping]
	now Cunt Adjective entry is ""; [one word adjective: avian/canine/...]
	now Cunt Change entry is ""; [partial sentence that fits in: "Your pussy [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Cunt change entry]."]
	now Cunt Description entry is ""; [partial sentence to fit: "You have a [Cunt Tightness Adjective of Player] [one of]cunt[or]pussy[or]vagina[or]cleft[at random] that [Cunt Description of Player]."]
	now Cunt Color entry is ""; [one word color descriptor]
	now Clit Size entry is 0; [size 1-5, see Clit Size Adjective]
	[Clit Size Adjective is generated by a function and can be used in scenes: very small/small/average/large/very large]
]


Section 3 - Endings

Table of GameEndings (continued)
Name (text)	Type (text)	Subtype (text)	Ending (rule)	Priority (number)	Triggered (truth state)
"Stallionboi Infection"	"Infection"	""	Stallionboi Infection rule	1000	false

This is the Stallionboi Infection rule:
	if Player has a body of "Stallionboi":
		trigger ending "Stallionboi Infection"; [Here it states, that the ending has been played.]
		if humanity of Player < 10:
			if Player is male:
				say "     Unable to deny your body the sexual pleasure and stimulation it craves, you quickly run back to the wonderful stables, and all the sexy stallionbois you just know are waiting for you there. The guards smirk with amusement as you rush by, their eyes drawn to your sexy little part equine body, causing you to shudder happily at the thought of the more powerful horsemen using you like a good little pet again and again. Once inside, you quickly charge off down the halls, finding yourself nearly squealing with joy as your lust fogged mind follows the scent of equine sex through the halls. It isn't long before another of those sexy stallionbois finds you, and he grins happily and squeals with pleasure as you practically throw yourself onto him, leading you through the corridors quickly to where the rest of the stallionbois are waiting for you eagerly with arms wide open, and cocks already erect. It isn't long before they fuck any last remaining doubts about being a sexy slutty stallionboi out of you, teaching you all about how to be a proper little stallionslut and how to service any client or mare (or stallion!) that wants to use your slutty little body. And you find yourself smiling happily as you learn to be a proper little submissive femboi, finding yourself strangely happy with your new feminine like part horse form, as the more horselike mares and stallions go about the business of the place, you find yourself eagerly looking forward to your new life of sex and pleasure serving their every whim...";
			else:
				say "     Unable to deny your body the sexual pleasure and stimulation it craves, you quickly run back to the wonderful stables, and all the sexy stallionbois you just know are waiting for you there. The guards smirk with amusement as you rush by, their eyes drawn to your sexy little part equine body, causing you to shudder happily at the thought of the more powerful horsemen using you like a good little pet again and again. Once inside, you quickly charge off down the halls, finding yourself nearly squealing with joy as your lust fogged mind follows the scent of equine sex through the halls. It isn't long before another of those sexy stallionbois finds you, and he grins happily and squeals with pleasure as you practically throw yourself onto him, leading you through the corridors quickly to where the rest of the stallionbois are waiting for their slutty little stallionpussy with arms wide open, and cocks already erect. It isn't long before they fuck any last remaining doubts about being a sexy slutty stallionslave out of you, teaching you all about how to be a proper little stallionslut and how to service any client or mare (or stallion!) that wants to use your slutty little body, teaching you how to use your pussy and mouth properly to please any master who wants you. And you find yourself smiling happily as you learn to be a proper little submissive femme, finding yourself strangely happy with your new feminine like part horse form, and as the more horselike mares and stallions go about the business of the place, you find yourself eagerly looking forward to your new life of sex and pleasure serving their every whim...";
		else:
			if Player is male:
				say "     When the rescue finally comes, you find yourself unable to resist as the powerful military men come and take you away to safety, something about their strong well toned bodies and purposeful actions making you feel rather mild and meek as they lead you away. Eventually after being poked and prodded by several of their scientists, when they can't figure out what to do with you otherwise, they end up letting you go, having deemed you to not be a threat to society, and focus their attentions back on the fight raging throughout the city. Free, you find yourself drifting for a while, unable to find much purpose or direction in your life as you wander around aimlessly. You soon realize that you are far more girlish and submissive than ever before, and are unable to put yourself forward, or deny most dominant people whatever it is they want. This results in you taking a number of jobs, and eventually slinking away from them quietly when the people there begin to realize this and start to take advantage of you. Finally you find yourself making some friends with a few sympathetic women one night, and they help you to get a job at a sexy clothing store for women. You find yourself beginning to enjoy your work again, and growing somewhat more comfortable with the place, although the female owner does think it is fun sometimes to dress your feminine form up in some of the clothing around the place. You actually find yourself amused by this as well sometimes, the feel of silk and leather on your sensitive skin making you feel quite nice and slutty, and the looks on some of the men's faces when they realize you are packing a large equine cock is hilarious sometimes. Of course eventually you do manage to find a few men and women willing to experiment with your sexy new body, including of course most of your co workers, who soon come to love being just as sexy and slutty as you do. Eventually your owner decides to start branching out the direction of the store, and you just love the thought of how much fun you are going to have with all the new lovely sex toys and bondage gear she is stocking up in back for the customers... or to use on the customers... you just can't wait to try it out yourself!";
			else:
				say "     When the rescue finally comes, you find yourself unable to resist as the powerful military men come and take you away to safety, something about their strong well toned bodies and purposeful actions making you feel rather mild and meek as they lead you away. While they quickly dismiss you as relatively harmless compared to the more dangerous beasts within the city, you find yourself somewhat less than willing to leave right away, spending your time at the base helping the soldiers fetch things and take care of any small tasks they might need your help with. The more time you spend in the presence of the sexy and dominant men, the less you find yourself wanting to leave, somehow craving the sense of safety and security being surrounded by the soldiers gives you. When one of them inevitably takes you off into a dark corner to put your sexy little mare pussy to use, you find yourself squealing happily as your body responds eagerly to his touch. Once you realize how amazing it feels to serve your rescuers with your body, you waste no time in doing so at every opportunity, spreading your legs for them eagerly as often as possible. Before long, you find yourself hardly even thinking of them as soldiers anymore, and start thinking of the sexy uniform clad men as your masters instead. As things get worse and worse in the city, the military turns a blind eye (perhaps helped by how often some of your higher ranked masters enjoy using you) to your presence, you enjoy your new position more and more. And when eventually some of your sexy masters start showing even more handsome equine features, you don't hesitate to send them in the direction of the stables, where you assure them they can find all sorts of horsey fun when they go into the city. And while few of them come back from venturing into that part of the city, and those that do only stay back long enough to take a few friends with them as they head back out, and as the military encampment slowly shrinks in size, and the numbers of sexy horsemen in the city swells larger, you have a feeling you will be seeing many of your now horsey masters again soon enough, in the meantime, there are still plenty of sexy masters willing to use your slutty equine body as often as possible... with more arriving every day...";

Stallionboi ends here.
